= Exercises solutions and hints

Don't expect to find *all* the answers here :)


== Chapter 13: the Probabilitic Method

=== 13.3.4

The crux of the exercise is in a)ii), which boils down to proving the following analysis result: `(exp(x) + exp(-x))/2 <= exp(x^2 / 2)`.

It looks like high-school math, but it's surprisingly more difficult; you have multiplications inside the exponential and additions outside, which is exactly the opposite of what you want. I've had great fun challenging my scientifically-inclined friends with this problem, it usually drives them crazy in a matter of hours (if that's any consolation to them, it took me half a dozen attempts, spread over 2 days). **Hint** in 3, 2, 1...

Hint: write each side of the result as power series.

== Chapter 16: Matchings

=== 16.1.15

I'm currently at a loss for this one. I've seen online solutions using the König-Egervary Theorem, but the exercise is actually intended as a Lemma for this theorem.

The result is easily deduced from Lemma 16.10 2 sections later, so maybe the proof of 16.10 could be adapted for this special case.

=== 16.2.7

Not that easy IMHO!

a) I prove that any edge `e`, joining `x` to `y`, us covered. Nothing to prove if `x` is not in `Z`. If `x` is in `Z`, consider an M-alternating path starting from U ending in x; prove it either contains y or can be extended to end in y, as in the latter case x would not be matched to y.

b) 2 observations here:

* all vertices in X \ R are matched (as U is contained in R)
* a vertex in X \ R is never matched to a vertex in B

Counting the matched vertices in Y, it then follows that |M*| is greater than or equal to |X\Z| + |B|, which is exactly |K*|.

=== 16.2.8

Not easy either IMHO. There's an error in the problem statement: it's actually |S| - |N(S)| in a).

The hard part of the exercise is the 'if' part of a)ii): let M a maximum matching, and S the set of vertices in X reachable from U by M-alternating paths. Note that S contains U.

Use Berge's theorem to prove that all neighbours of S are matched to a vertex of S (I decomposed S into matched and unmatched vertices, then you get `|N(S)| = |N(S\U)| = |S\U| = |S| - |U|`). 



=== 16.2.11

I answered that one https://math.stackexchange.com/a/3231948/141752[here].


=== 16.2.18

You prove that there's a permutation matrix which support is contained in the support of Q, then use induction.

To get the first result, you model this with a bipartite graph which vertices are the lines of Q (rows on the left, columns on the right), and the edges are the non-zero entries of Q, each incident to the row and line containing it. Hall's condition can be deduced by considering row sums and column sums.

=== 16.2.20

You model this problem by a bipartite graph where the vertices are the left cosets on one side and the right cosets on the other. The edges are the elements of H, each joining to left and right cosets to which it belongs. The problem reduces then to proving that there's a perfect matching in this graph.

It's worth noting that the left cosets are the equivalence classes by the equivalence relation of being 'right-proportional', i.e `x = y.k` where `k` is in K. Likewise for right cosets, except it's not the same equivalence relation. 

Therefore each coset has `|K|` elements, i.e all vertices of G have degree |K|; the Hall condition can be deduced from that.

=== 16.2.27

No difficulty in a), it's the same as for finite graphs.

My counterexample is a graph which vertices are the natural integers, each `n` joined to `n+1`, plus an additional vertex `x` joined to all odd integers. Assuming a perfect matching, and considering the odd integer matched to `x`, it follows that `0` can't be matched.

Now I wondered if I cheated by using a vertex of infinite degree. AFAICT, it turns out that if you forbid infinite degrees, then there is no counter example. I view this as a consequence of the https://en.wikipedia.org/wiki/Compactness_theorem[Compactness Theorem] of boolean logic: each edge is a boolean variable, and a matching is an assignment of truth that satisfies a set of boolean formulas. I find this rather neat actually: Hall's theorem gives you full matchings for finite subgraphs, then the compactness theorem generalizes to the whole graph.

=== 16.3.8

**ERRATUM:** the final result is not quite correct; it should be "a **connected** graph is hypomatchable iff the empty set is its only barrier", or the more general "the **components of a graph** are hypomatchable iff the empty set is its only barrier."

a) 

i) The problem statement should be "a **connected** graph is hypomatchable iff each of its blocks is hypomatchable". Both direction of the equivalence can be proved by induction on the number of blocks. Considering a separating vertex `s` separating G into two subgraphs `H` and `H'`, and a vertex `v` of H, consider how to construct a perfect matching of `G-v` can be built from / decomposed into perfect matchings of `H-v` and `H'-s`.

   ii) The 'only if' part is easily proved by applying (16.2). For the 'if' part, you first deduce from Tutte-Berge that the empty set is the only barrier of G (it's the only one that might achieve equality in (16.3)). You can then first prove the result for a non-separable graph, applying the inequality for `S = {v}` to deduce that `G-v` is matchable by Tutte-Berge. You can then prove that the hypothesis inequality applies to each block of G; to do that, it helps to picture the blocks-decomposition-tree of G, and observe that the all blocks of G are odd; you can then prove that the components of `G-S` can be obtained from the components of `H-s` by either adding separate components or extending components of `H-S` with an even number of vertices, and so `H-S` has no more odd components than `G-S`. Finally you apply a)i).

b) The 'if' part is the hard one. For a vertex `v`, and a proper subset `S` of `V`, observe the equivalence `(G-v)-S = G-(S∪{v})`; use the fact that `S∪{v}` is not a barrier of G to show that `G-v` is matchable with the Tutte-Berge formula, making a case analysis between G even (`o(G) = 0`) and odd (`o(G) = 1`).

